### PR TITLE
Fix error message test.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by tonyg** [comment]
Thanks, Sam. I've changed the test to run with older versions too.

**Comment by jbclements** [comment]
@tonyg I'm going to mark this issue as no longer blocking the release. That is, it doesn't appear that this failing test has uncovered a problem that needs to be fixed in Racket. Let me know if I'm mistaken!

**Comment by samth** [comment]
@jbclements I believe there was a (now-addressed) failure with the pkg server which is why the update here hasn't yet led to a fixed pkg build. That should happen within a couple days.

**Comment by jbclements** [comment]
Hmm... it looks to me like this was only merged yesterday, which (I think) is why the fix doesn't show up in pkg-build-diff yet. Either way, I think the prognosis is the same.

**Pull request merged**
